defaultSemverRangePrefix: ""

npmRegistries:
  "https://gitlab.com/api/v4/packages/npm/":
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN_STERBLUE_GITLAB}"

npmScopes:
  sterblue:
    npmRegistryServer: "https://gitlab.com/api/v4/packages/npm/"

packageExtensions:
  "@types/jest@*":
    dependencies:
      "@types/jest-diff": "*"
      jest-diff: "*"

plugins:
  - ./.yarn/plugins/light-yarn/index.js
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.3.3.cjs
