defaultSemverRangePrefix: ""

npmRegistries:
  "https://gitlab.com/api/v4/packages/npm/":
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN_STERBLUE_GITLAB}"

npmScopes:
  sterblue:
    npmRegistryServer: "https://gitlab.com/api/v4/packages/npm/"

packageExtensions:
  "@types/jest@*":
    dependencies:
      "@types/jest-diff": "*"
      jest-diff: "*"
  "@storybook/core@*":
    peerDependencies:
      "@storybook/addon-essentials": "*"
      "@storybook/preset-typescript": "*"
  "@storybook/react@*":
    peerDependencies:
      "@storybook/addon-essentials": "*"
      "@storybook/preset-typescript": "*"
  # "@storybook/addon-actions@6.0.0-beta.32":
  #   peerDependencies:
  #     "@storybook/core": "*"
  #     react-dom: "*"
  # "@storybook/addon-actions@^5.0.0 || ^4.0.0":
  #   peerDependencies:
  #     "@emotion/core": "*"
  #     "@storybook/core": "*"
  #     react-dom: "*"
  # "@storybook/addon-knobs@^5.0.0 || ^4.0.0":
  #   peerDependencies:
  #     "@emotion/core": "*"
  #     "@storybook/core": "*"
  #     react-dom: "*"
  # "@storybook/addon-knobs@^6.0.0-beta.32":
  #   peerDependencies:
  #     "@storybook/core": "*"
  # "@storybook/addon-links@^5.0.0 || ^4.0.0":
  #   peerDependencies:
  #     "@emotion/core": "*"
  #     "@storybook/core": "*"
  #     react-dom: "*"
  # "@storybook/addon-links@^6.0.0-beta.32":
  #   peerDependencies:
  #     "@storybook/core": "*"
  # "@storybook/addons@^5.0.0 || ^4.0.0":
  #   peerDependencies:
  #     "@emotion/core": "*"
  #     "@storybook/core": "*"
  #     react: "*"
  #     react-dom: "*"
  # "@storybook/addons@^6.0.0-beta.32":
  #   dependencies:
  #     "@types/webpack-env": "*"
  #   peerDependencies:
  #     "@storybook/core": "*"
  # "@storybook/api@^6.0.0-beta.32":
  #   peerDependencies:
  #     "@storybook/core": "*"
  # "@storybook/cli@^6.0.0-beta.32":
  #   peerDependencies:
  #     react: "*"
  #     react-dom: "*"
  # "@storybook/client-api@^5.0.0 || ^4.0.0":
  #   peerDependencies:
  #     "@emotion/core": "*"
  #     "@storybook/core": "*"
  #     react: "*"
  #     react-dom: "*"
  # "@storybook/client-api@^6.0.0-beta.32":
  #   peerDependencies:
  #     "@storybook/core": "*"
  #     react: "*"
  #     react-dom: "*"
  # "@storybook/codemod@^6.0.0-beta.32":
  #   dependencies:
  #     jest: "*"
  #   peerDependencies:
  #     "@babel/core": "*"
  #     react: "*"
  #     react-dom: "*"
  # "@storybook/components@^5.0.0 || ^4.0.0":
  #   peerDependencies:
  #     "@emotion/core": "*"
  #     "@storybook/core": "*"
  # "@storybook/components@^6.0.0-beta.32":
  #   peerDependencies:
  #     "@storybook/core": "*"
  # "@storybook/core@^5.0.0 || ^4.0.0":
  #   peerDependencies:
  #     "@babel/core": "*"
  #     "@emotion/core": "*"
  # "@storybook/mantra-core@*":
  #   peerDependencies:
  #     react: "*"
  # "@storybook/preset-typescript@3.0.0":
  #   peerDependencies:
  #     "@babel/core": "*"
  # "@storybook/react@^5.0.0 || ^4.0.0":
  #   peerDependencies:
  #     "@babel/core": "*"
  #     "@emotion/core": "*"
  # "@storybook/react@^6.0.0-beta.32":
  #   dependencies:
  #     "@types/node": "*"
  #   peerDependencies:
  #     "@babel/core": "*"
  #     typescript: ">= 3.x"
  # "@storybook/router@^5.0.0 || ^4.0.0":
  #   peerDependencies:
  #     "@storybook/core": "*"
  # "@storybook/theming@^5.0.0":
  #   peerDependencies:
  #     "@emotion/serialize": "*"
  #     "@emotion/utils": "*"
  #     "@storybook/core": "*"
  # "@storybook/theming@^6.0.0-beta.32":
  #   dependencies:
  #     "@emotion/serialize": "*"
  #     "@emotion/utils": "*"
  #   peerDependencies:
  #     "@storybook/core": "*"
  # "@storybook/ui@^5.0.0 || ^4.0.0":
  #   dependencies:
  #     "@babel/runtime": "*"
  #   peerDependencies:
  #     "@babel/core": "*"
  #     "@emotion/core": "*"
  #     "@storybook/core": "*"
  # "@storybook/ui@^6.0.0-beta.32":
  #   peerDependencies:
  #     "@storybook/core": "*"

plugins:
  - ./.yarn/plugins/light-yarn/index.js
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.3.3.cjs
